version: '2'

networks:
  hms_docker_k8s:

services:

  nginx:
    image: nginx:latest
    ports:
      - 8083:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    networks:
      - hms_docker_k8s

  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - database
        - redis
        - smtp
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - hms_docker_k8s

  database:
        image: mysql:5.7
        environment:
          - "MYSQL_ROOT_PASSWORD=common404"
          - "MYSQL_DATABASE=laravel"
          - "MYSQL_USERNAME=root"
        volumes:
          - ${BACKUP_DATA_PATH}/mysql3:/var/lib/mysql
        ports:
          - "33065:3306"
        networks:
          - hms_docker_k8s

  
  redis :
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    networks:
      - hms_docker_k8s

  smtp:
    image: namshi/smtp
    ports:
      - 587:587
    networks:
      - hms_docker_k8s

  
