apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: hms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: hms
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: hms
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "common404"
            - name: MYSQL_ROOT_PASSWORD
              value: "common404"
          args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5