apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
    app: hms
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80