apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    name: nginx-config
    app: hms
data:
  config: |
    server {
      index index.php index.html:
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;
      root /var/www/html/public;
      location / {
      try_files $uri $uri/ /index.php?$args;
      }
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php?$args;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
      }
    }