apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx-service
    app: hms
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    name: nginx-pod
    app: hms