apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    name: nginx-deploy
    app: hms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-pod
      app: hms
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx-pod
        app: hms
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80