apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: hms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: hms
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: hms
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379 